name: Build & Deploy -> Docker Hub
on:
  push:
    branches:
     - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set current date as env variable
      run: echo "TIME=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
    - name: Build app
      run: |
        npm ci
        npx eslint ./src --fix
        npm run build
    - name: Docker login
      run: echo "$PASSWORD" | docker login -u "$USER" --password-stdin
      env:
        USER: ${{ secrets.DOCKER_USERNAME }}
        PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build docker image
      run: |
        docker build -t techradarapi/techradar-api:F-$TIME .
        docker build -t techradarapi/techradar-api:F-latest .
    - name: Push docker image to Docker Hub
      run: |
        docker push techradarapi/techradar-api:F-$TIME
        docker push techradarapi/techradar-api:F-latest
