name: Deploy -> server
on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: SSH connect & deploy
      uses: cross-the-world/ssh-scp-ssh-pipelines@latest
      with:
        host: ${{ secrets.SSH_HOST }}
        user: ${{ secrets.SSH_USER }}
        pass: ${{ secrets.SSH_PASSWORD }}
        connect_timeout: 10s
        first_ssh: |
          cd ~/server
          sed '/FRONTEND_TAG/d' .env -i
          echo "FRONTEND_TAG=F-latest" >> .env
          ./frontend/deploy.sh
